# Site settings
title: Моя йога
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
copyright_name: Моя йога. Блог Татьяны Докторовой
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/myYoga"
twitter_username: myYoga
email_username:  your-email@yourdomain.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, kramdown, jekyll-watch]
